# Generated by Django 5.2.4 on 2025-08-31 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_category_display_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('None', 'None'), ('BOOKs', 'Books'), ('CLOTH', 'Clothing'), ('ELEC', 'Electronics'), ('FURN', 'Furniture'), ('TOYS', 'Toys'), ('SPORT', 'Sports Equipment'), ('MISC', 'Miscellaneous'), ('OTHER', 'Other'), ('VEHICLE', 'Vehicle'), ('JEWELRY', 'Jewelry'), ('HOME', 'Home Appliances'), ('GARDEN', 'Garden Supplies'), ('TOOLS', 'Tools'), ('ART', 'Art & Collectibles'), ('PETS', 'Pet Supplies')], default='', max_length=10),
        ),
    ]
