# Generated by Django 5.2.4 on 2025-09-05 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('None', 'None'), ('BOOKS', 'Books'), ('CLOTH', 'Clothing'), ('ELEC', 'Electronics'), ('FURN', 'Furniture'), ('TOYS', 'Toys'), ('SPORT', 'Sports Equipment'), ('MISC', 'Miscellaneous'), ('OTHER', 'Other'), ('VEHICLE', 'Vehicle'), ('JEWELRY', 'Jewelry'), ('HOME', 'Home Appliances'), ('GARDEN', 'Garden Supplies'), ('TOOLS', 'Tools'), ('ART', 'Art & Collectibles'), ('PETS', 'Pet Supplies')], default='', max_length=10),
        ),
    ]
