# Generated by Django 5.2.4 on 2025-09-06 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_category_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-name'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
