# Generated by Django 5.2.4 on 2025-09-17 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='display_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('BOOKS', 'Books'), ('CLOTHING', 'Clothing'), ('ELECTRONICS', 'Electronics'), ('FURNITURE', 'Furniture'), ('TOYS', 'Toys'), ('SPORTS', 'Sports Equipment'), ('MISCELLANEOUS', 'Miscellaneous'), ('OTHER', 'Other'), ('VEHICLE', 'Vehicle'), ('JEWELRY', 'Jewelry'), ('HOME', 'Home Appliances'), ('GARDEN', 'Garden Supplies'), ('TOOLS', 'Tools'), ('ART AND COLLECTIBLES', 'Art & Collectibles'), ('PETS AND PET SUPPLIES', 'Pet Supplies')], max_length=100, unique=True),
        ),
    ]
