# Generated by Django 5.2.4 on 2025-09-28 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_category_products_ca_name_693421_idx'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
